# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e2cde6585d49b4a2677e907cf51b0fc13601eeddc7e267cc0353e9030b0677a025c0ebe73b50e564f68e582585f4bbac83097362b1b417a0493a6223e821753

test:
  secret_key_base: 5a75f44336dc1807abc5b9251d7b1831ad53376eabef900c343f67a00fe0d96e75e78ee0f263e0c0e86c3983b3fc0801edf0f21a08c4633eecf0f514360add95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
